name: ESLint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint .

      - name: Run Tests
        env:
              API_KEY: ${{ secrets.API_KEY }}
              AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
              PROJECT_ID: ${{ secrets.PROJECT_ID }}
              STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
              MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
              APP_ID: ${{ secrets.APP_ID }}
        run: npm test

      - name: Run Snyk test
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: npm run snyk

  deploy:
    name: Deploy to Render.com
    needs: lint # Wait for the 'lint' job to finish before triggering the 'deploy' job

    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render.com deploy hook
        env: # Define an environment variable to store the secret value
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }} # Use the name of the secret you created
        run: curl -X POST $RENDER_DEPLOY_HOOK # Use the environment variable to access the secret value
